version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - build_folder:/var/www/frontend
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      - mysql
    command: >
        bash -c "python manage.py makemigrations &&
                python manage.py migrate &&
                gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.prod
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/frontend
      - build_folder:/frontend/dist
      - /frontend/node_modules

volumes:
  build_folder: null